package typescript

import (
	"io/ioutil"
	"os"
	"path/filepath"
	"testing"

	"github.com/kapok/kapok/pkg/codegen"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestClientGenerator_GenerateClient(t *testing.T) {
	generator := NewClientGenerator()

	schema := &codegen.Schema{
		Tables: []*codegen.Table{
			{
				Name:   "users",
				Schema: "public",
				Columns: []*codegen.Column{
					{Name: "id", DataType: "integer", IsNullable: false},
					{Name: "email", DataType: "varchar", IsNullable: false},
				},
				PrimaryKey: &codegen.PrimaryKey{ColumnNames: []string{"id"}},
			},
		},
	}

	result := generator.GenerateClient(schema)

	// Verify imports
	assert.Contains(t, result, "import {")
	assert.Contains(t, result, "Users,")
	assert.Contains(t, result, "CreateUsersInput,")
	assert.Contains(t, result, "UpdateUsersInput,")

	// Verify class declaration
	assert.Contains(t, result, "export class KapokClient")
	assert.Contains(t, result, "constructor(private baseUrl: string)")

	// Verify users methods
	assert.Contains(t, result, "users = {")
	assert.Contains(t, result, "create: (input: CreateUsersInput)")
	assert.Contains(t, result, "getById: (id: number)")
	assert.Contains(t, result, "list: (options?: { limit?: number; offset?: number })")
	assert.Contains(t, result, "update: (id: number, input: UpdateUsersInput)")
	assert.Contains(t, result, "delete: (id: number)")
}

func TestClientGenerator_GenerateIndexFile(t *testing.T) {
	generator := NewClientGenerator()

	schema := &codegen.Schema{
		Tables: []*codegen.Table{
			{Name: "users", Schema: "public"},
		},
	}

	result := generator.GenerateIndexFile(schema)

	assert.Contains(t, result, "export * from './types'")
	assert.Contains(t, result, "export * from './api'")
	assert.Contains(t, result, "export { KapokClient } from './client'")
	assert.Contains(t, result, "Auto-generated by Kapok")
}

func TestClientGenerator_GenerateTypesIndexFile(t *testing.T) {
	generator := NewClientGenerator()

	schema := &codegen.Schema{
		Tables: []*codegen.Table{
			{
				Name:   "users",
				Schema: "public",
				Columns: []*codegen.Column{
					{Name: "id", DataType: "integer", IsNullable: false},
					{Name: "email", DataType: "varchar", IsNullable: false},
				},
			},
		},
	}

	result := generator.GenerateTypesIndexFile(schema)

	assert.Contains(t, result, "export interface Users")
	assert.Contains(t, result, "export interface CreateUsersInput")
	assert.Contains(t, result, "export interface UpdateUsersInput")
}

func TestClientGenerator_GenerateAPIIndexFile(t *testing.T) {
	generator := NewClientGenerator()

	schema := &codegen.Schema{
		Tables: []*codegen.Table{
			{
				Name:   "users",
				Schema: "public",
				Columns: []*codegen.Column{
					{Name: "id", DataType: "integer", IsNullable: false},
				},
				PrimaryKey: &codegen.PrimaryKey{ColumnNames: []string{"id"}},
			},
		},
	}

	result := generator.GenerateAPIIndexFile(schema)

	// Verify imports
	assert.Contains(t, result, "import {")
	assert.Contains(t, result, "} from '../types'")

	// Verify all CRUD functions
	assert.Contains(t, result, "export async function createUsers(")
	assert.Contains(t, result, "export async function getUsersById(")
	assert.Contains(t, result, "export async function listUsers(")
	assert.Contains(t, result, "export async function updateUsers(")
	assert.Contains(t, result, "export async function deleteUsers(")
}

func TestClientGenerator_GeneratePackageJSON(t *testing.T) {
	generator := NewClientGenerator()

	result, err := generator.GeneratePackageJSON("my-kapok-sdk")
	require.NoError(t, err)

	assert.Contains(t, result, `"name": "my-kapok-sdk"`)
	assert.Contains(t, result, `"version": "0.1.0"`)
	assert.Contains(t, result, `"typescript"`)
	assert.Contains(t, result, `"build": "tsc"`)
	assert.Contains(t, result, `"MIT"`)
}

func TestClientGenerator_GenerateTSConfig(t *testing.T) {
	generator := NewClientGenerator()

	result, err := generator.GenerateTSConfig()
	require.NoError(t, err)

	assert.Contains(t, result, `"target": "ES2020"`)
	assert.Contains(t, result, `"module": "commonjs"`)
	assert.Contains(t, result, `"declaration": true`)
	assert.Contains(t, result, `"strict": true`)
	assert.Contains(t, result, `"src/**/*"`)
}

func TestClientGenerator_WriteSDK(t *testing.T) {
	generator := NewClientGenerator()

	schema := &codegen.Schema{
		Tables: []*codegen.Table{
			{
				Name:   "users",
				Schema: "public",
				Columns: []*codegen.Column{
					{Name: "id", DataType: "integer", IsNullable: false},
					{Name: "email", DataType: "varchar", IsNullable: false},
				},
				PrimaryKey: &codegen.PrimaryKey{ColumnNames: []string{"id"}},
			},
		},
	}

	// Create temporary directory
	tmpDir, err := ioutil.TempDir("", "sdk-test-*")
	require.NoError(t, err)
	defer os.RemoveAll(tmpDir)

	// Write SDK
	err = generator.WriteSDK(tmpDir, schema, "test-sdk")
	require.NoError(t, err)

	// Verify directory structure
	expectedDirs := []string{
		filepath.Join(tmpDir, "src"),
		filepath.Join(tmpDir, "src", "types"),
		filepath.Join(tmpDir, "src", "api"),
	}

	for _, dir := range expectedDirs {
		info, err := os.Stat(dir)
		require.NoError(t, err)
		assert.True(t, info.IsDir())
	}

	// Verify files exist
	expectedFiles := []string{
		filepath.Join(tmpDir, "package.json"),
		filepath.Join(tmpDir, "tsconfig.json"),
		filepath.Join(tmpDir, "README.md"),
		filepath.Join(tmpDir, "src", "index.ts"),
		filepath.Join(tmpDir, "src", "client.ts"),
		filepath.Join(tmpDir, "src", "types", "index.ts"),
		filepath.Join(tmpDir, "src", "api", "index.ts"),
	}

	for _, file := range expectedFiles {
		_, err := os.Stat(file)
		require.NoError(t, err, "File should exist: %s", file)
	}

	// Verify file contents
	indexContent, err := ioutil.ReadFile(filepath.Join(tmpDir, "src", "index.ts"))
	require.NoError(t, err)
	assert.Contains(t, string(indexContent), "export * from './types'")

	packageJSON, err := ioutil.ReadFile(filepath.Join(tmpDir, "package.json"))
	require.NoError(t, err)
	assert.Contains(t, string(packageJSON), "test-sdk")
}

func TestClientGenerator_MultipleTablesIntegration(t *testing.T) {
	generator := NewClientGenerator()

	schema := &codegen.Schema{
		Tables: []*codegen.Table{
			{
				Name:   "users",
				Schema: "public",
				Columns: []*codegen.Column{
					{Name: "id", DataType: "integer", IsNullable: false},
					{Name: "email", DataType: "varchar", IsNullable: false},
				},
				PrimaryKey: &codegen.PrimaryKey{ColumnNames: []string{"id"}},
			},
			{
				Name:   "posts",
				Schema: "public",
				Columns: []*codegen.Column{
					{Name: "id", DataType: "uuid", IsNullable: false},
					{Name: "title", DataType: "text", IsNullable: false},
					{Name: "user_id", DataType: "integer", IsNullable: false},
				},
				PrimaryKey: &codegen.PrimaryKey{ColumnNames: []string{"id"}},
			},
		},
	}

	client := generator.GenerateClient(schema)

	// Verify both tables have methods
	assert.Contains(t, client, "users = {")
	assert.Contains(t, client, "posts = {")

	// Verify different PK types
	assert.Contains(t, client, "getById: (id: number) => getUsersById")   // integer PK
	assert.Contains(t, client, "getById: (id: string) => getPostsById")   // uuid PK
}

func TestClientGenerator_ReadmeGeneration(t *testing.T) {
	generator := NewClientGenerator()

	readme := generator.generateReadme("my-sdk")

	assert.Contains(t, readme, "# my-sdk")
	assert.Contains(t, readme, "## Installation")
	assert.Contains(t, readme, "## Usage")
	assert.Contains(t, readme, "KapokClient")
	assert.Contains(t, readme, "Generated by [Kapok]")
}

func TestClientGenerator_EmptySchema(t *testing.T) {
	generator := NewClientGenerator()

	schema := &codegen.Schema{
		Tables: []*codegen.Table{},
	}

	// Should not panic with empty schema
	result := generator.GenerateClient(schema)
	assert.Contains(t, result, "export class KapokClient")
	assert.Contains(t, result, "constructor(private baseUrl: string)")
}
